- purl: pkg:rpm/redhat/molecule@24.9.0-2.el8ap?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:9894
- purl: pkg:rpm/redhat/molecule@24.9.0-2.el8ap?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:9894
