- purl: pkg:deb/ubuntu/gitlab-ci-multi-runner@11.2.0%2Bdfsg-2ubuntu1?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-13295
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-13327
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-39939
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-39947
  fixing_advisories: []
