- purl: pkg:deb/ubuntu/grafana@2.6.0%2Bdfsg-1?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv/UBUNTU-CVE-2024-10452
    - ubuntu_osv/UBUNTU-CVE-2024-11741
    - ubuntu_osv/UBUNTU-CVE-2024-1313
    - ubuntu_osv/UBUNTU-CVE-2024-1442
    - ubuntu_osv/UBUNTU-CVE-2024-6322
    - ubuntu_osv/UBUNTU-CVE-2024-8118
    - ubuntu_osv/UBUNTU-CVE-2024-9264
    - ubuntu_osv/UBUNTU-CVE-2024-9476
    - ubuntu_osv/UBUNTU-CVE-2026-21727
  fixing_advisories: []
