- purl: pkg:pypi/ansible@2.6.0rc4
  affected_by_advisories:
    - pysec/PYSEC-2019-171
    - pysec/PYSEC-2019-2
    - pysec/PYSEC-2019-4
    - pysec/PYSEC-2019-72
    - pysec/PYSEC-2019-74
    - pysec/PYSEC-2020-10
    - pysec/PYSEC-2020-11
    - pysec/PYSEC-2020-12
    - pysec/PYSEC-2020-161
    - pysec/PYSEC-2020-180
    - pysec/PYSEC-2020-210
    - pysec/PYSEC-2020-220
    - pysec/PYSEC-2020-221
    - pysec/PYSEC-2020-3
    - pysec/PYSEC-2020-5
    - pysec/PYSEC-2020-6
    - pysec/PYSEC-2020-7
    - pysec/PYSEC-2020-8
    - pysec/PYSEC-2020-9
    - pysec/PYSEC-2021-1
    - pysec/PYSEC-2021-105
    - pysec/PYSEC-2021-106
    - pysec/PYSEC-2021-124
    - pysec/PYSEC-2021-125
    - pysec/PYSEC-2021-126
  fixing_advisories: []
